Repository dexidp/dex, pull requests merged in 2018-09, with the labels that each got.

#1285 connectors/ldap: treat 'constraint violation' on bind as bad credentials
  connector/ldap/ldap.go
Labels: area/connectors

#1266 fix timeout bug for etcd3 client connect
  storage/etcd/config.go
Labels: kind/bug

#1296 scripts,Makefile: nuke check-go-version
  Makefile
  scripts/check-go-version
Labels: kind/cleanup

#1290 release process: update quay notes
  Documentation/dev-releases.md
  Makefile
  examples/k8s/dex.yaml
Labels: area/distribution, kind/documentation
