Repository dexidp/dex, pull requests merged in 2019-12, with the labels that each got.

#1591 connector/google: support group whitelisting
  Documentation/connectors/google.md
  connector/google/google.go
Labels: area/connectors

#1596 Add github actions CI flow
  .github/workflows/.editorconfig
  .github/workflows/ci.yml
  connector/ldap/ldap_test.go
  connector/ldap/testdata/certs/ca.crt
  connector/ldap/testdata/certs/ca.key
  connector/ldap/testdata/certs/dhparam.pem
  connector/ldap/testdata/certs/ldap.crt
  connector/ldap/testdata/certs/ldap.key
  connector/ldap/testdata/core.schema
  connector/ldap/testdata/cosine.schema
  connector/ldap/testdata/inetorgperson.schema
  connector/ldap/testdata/misc.schema
  connector/ldap/testdata/nis.schema
  connector/ldap/testdata/openldap.schema
  go.mod
  go.sum
  storage/sql/config_test.go
  storage/sql/postgres_test.go
Labels: area/developer tooling

#1556 storage: conformance tests improvements
  storage/conformance/conformance.go
  storage/conformance/transactions.go
Labels: area/testing
