Repository dexidp/dex, pull requests merged in 2019-07, with the labels that each got.

#1480 connectors: refactor filter code into a helper package
  connector/bitbucketcloud/bitbucketcloud.go
  connector/github/github.go
  connector/gitlab/gitlab.go
  connector/microsoft/microsoft.go
  go.mod
  pkg/groups/groups.go
  pkg/groups/groups_test.go
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: area/connectors, kind/cleanup

#1497 connector/gitlab: implement useLoginAsID as in GitHub connector
  Documentation/connectors/gitlab.md
  connector/github/github.go
  connector/gitlab/gitlab.go
  connector/gitlab/gitlab_test.go
Labels: area/connectors

#1502 server/api: fix logging in VerifyPassword
  server/api.go
Labels: kind/bug
