Repository dexidp/dex, pull requests merged in 2021-05, with the labels that each got.

#2124 Update etcd to 3.5.0-beta.3
  go.mod
  go.sum
  storage/etcd/config.go
Labels: area/dependencies, area/storage

#2141 Update gosundheit
  cmd/dex/serve.go
  go.mod
  go.sum
  server/handlers_test.go
  storage/health.go
Labels: area/dependencies

#2144 Bump golag-ci lint version to 1.40.1
  .golangci.yml
  Makefile
  server/handlers.go
  server/oauth2.go
  storage/ent/client/offlinesession.go
  storage/memory/memory.go
  storage/storage.go
Labels: area/dx
