Repository dexidp/dex, pull requests merged in 2021-02, with the labels that each got.

#1952 fix: return invalid_grant error for invalid or expired auth codes
  server/handlers.go
  server/handlers_test.go
Labels: area/oidc-spec, kind/bug

#1773 Add c_hash to id_token, issued on /auth endpoint, when in hybrid flow
  server/handlers.go
  server/oauth2.go
Labels: area/oidc-spec, kind/enhancement

#1997 Rewrite LDAP tests to use a single server instance
  .github/workflows/ci.yaml
  connector/ldap/ldap_test.go
  connector/ldap/testdata/schema.ldif
  docker-compose.override.yaml.dist
  docker-compose.test.yaml
  docker-compose.yaml
  go.mod
  go.sum
Labels: area/connector, area/testing, kind/enhancement

#2019 Refactor run groups
  cmd/dex/serve.go
Labels: kind/regression
