Repository dexidp/dex, pull requests merged in 2021-01, with the labels that each got.

#1908 Fix the etcd PKCE AuthCode deserialization
  storage/conformance/conformance.go
  storage/etcd/etcd.go
  storage/etcd/types.go
Labels: kind/bug

#1925 Update project dependencies
  go.mod
  go.sum
Labels: kind/dependencies

#1951 fix: update auth methods and claims from discovery endpoint
  server/handlers.go
Labels: area/oidc-certification, kind/enhancement

#1948 Add Cache-control headers to token responses
  server/deviceflowhandlers.go
  server/handlers.go
  server/server_test.go
Labels: area/oidc-spec, kind/enhancement

#1956 fix: unsupported request parameter error
  server/oauth2.go
  server/server_test.go
Labels: area/oidc-spec

#1958 Generic docker improvements
  Dockerfile
Labels: area/distribution, kind/enhancement
