Repository dexidp/dex, pull requests merged in 2021-06, with the labels that each got.

#2091 chore: test Kubernetes storage with KinD
  .github/workflows/ci.yaml
  Makefile
  go.mod
  go.sum
  storage/kubernetes/storage_test.go
Labels: area/testing

#2161 Update etcd
  go.mod
  go.sum
Labels: area/dependencies

#2189 Fix anonymous ldap bind
  connector/ldap/ldap.go
Labels: area/connector, kind/bug
