Repository dexidp/dex, pull requests merged in 2022-08, with the labels that each got.

#2620 updated gomplate version and added ppc64le support
  .github/workflows/artifacts.yaml
  .github/workflows/docker.yaml
  Dockerfile
Labels: release-note/new-feature

#2639 fix: Fallback when group claim is a string instead of an array of strings
  connector/oidc/oidc.go
  connector/oidc/oidc_test.go
Labels: release-note/enhancement

#2641 chore: Bump Go to 1.19
  Dockerfile
  go.mod
  go.sum
Labels: release-note/dependency-update
