Repository dexidp/dex, pull requests merged in 2022-07, with the labels that each got.

#2591 Add expiry.refreshToken settings to config.yaml.dist
  config.yaml.dist
Labels: release-note/ignore

#2352 Use GitLab's refresh_token during Refresh.
  connector/gitlab/gitlab.go
  connector/gitlab/gitlab_test.go
Labels: area/connector, release-note/enhancement

#2586 Add domainHint parameter to Microsoft Connector
  connector/microsoft/microsoft.go
  connector/microsoft/microsoft_test.go
Labels: area/connector, release-note/enhancement

#2584 grpc-client: Do not crash on empty response
  examples/grpc-client/client.go
Labels: release-note/bug-fix

#2575 add PKCE support to device code flow
  server/deviceflowhandlers.go
  server/deviceflowhandlers_test.go
  storage/conformance/conformance.go
  storage/ent/client/devicetoken.go
  storage/ent/client/types.go
  storage/ent/db/devicetoken.go
  storage/ent/db/devicetoken/devicetoken.go
  storage/ent/db/devicetoken/where.go
  storage/ent/db/devicetoken_create.go
  storage/ent/db/devicetoken_update.go
  storage/ent/db/migrate/schema.go
  storage/ent/db/mutation.go
  storage/ent/db/runtime.go
  storage/ent/schema/devicetoken.go
  storage/etcd/etcd.go
  storage/etcd/types.go
  storage/kubernetes/types.go
  storage/sql/crud.go
  storage/sql/migrate.go
  storage/storage.go
Labels: area/oidc-spec, release-note/new-feature

#2582 add config to explicitly set scopes for microsoft connector
  connector/microsoft/microsoft.go
Labels: release-note/enhancement
