Repository dexidp/dex, pull requests merged in 2022-04, with the labels that each got.

#2428 Update ent
  go.mod
  go.sum
  storage/ent/db/authcode_create.go
  storage/ent/db/authcode_query.go
  storage/ent/db/authcode_update.go
  storage/ent/db/authrequest_create.go
  storage/ent/db/authrequest_query.go
  storage/ent/db/authrequest_update.go
  storage/ent/db/client.go
  storage/ent/db/connector_create.go
  storage/ent/db/connector_query.go
  storage/ent/db/connector_update.go
  storage/ent/db/devicerequest_create.go
  storage/ent/db/devicerequest_query.go
  storage/ent/db/devicerequest_update.go
  storage/ent/db/devicetoken_create.go
  storage/ent/db/devicetoken_query.go
  storage/ent/db/devicetoken_update.go
  storage/ent/db/ent.go
  storage/ent/db/keys_create.go
  storage/ent/db/keys_query.go
  storage/ent/db/keys_update.go
  storage/ent/db/migrate/migrate.go
  storage/ent/db/mutation.go
  storage/ent/db/oauth2client_create.go
  storage/ent/db/oauth2client_query.go
  storage/ent/db/oauth2client_update.go
  storage/ent/db/offlinesession_create.go
  storage/ent/db/offlinesession_query.go
  storage/ent/db/offlinesession_update.go
  storage/ent/db/password_create.go
  storage/ent/db/password_query.go
  storage/ent/db/password_update.go
  storage/ent/db/refreshtoken_create.go
  storage/ent/db/refreshtoken_query.go
  storage/ent/db/refreshtoken_update.go
  storage/ent/db/runtime/runtime.go
  storage/ent/db/tx.go
  storage/ent/mysql.go
  storage/ent/postgres.go
  storage/ent/sqlite.go
Labels: area/storage

#2474 New docker image build
  .github/workflows/artifacts.yaml
Labels: area/distribution

#2478 Publish official distroless images
  .github/workflows/artifacts.yaml
  .github/workflows/docker.yaml
  Dockerfile
Labels: area/distribution, release-note/new-feature

#1789 Feature: groups in Gitea
  README.md
  connector/gitea/gitea.go
Labels: kind/enhancement, area/connector

#2487 Build multi-platform images in a single build job
  .github/workflows/artifacts.yaml
Labels: kind/bug
