Repository dexidp/dex, pull requests merged in 2022-09, with the labels that each got.

#2643 feat(connector/authproxy): support multiple groups
  connector/authproxy/authproxy.go
  connector/authproxy/authproxy_test.go
Labels: release-note/enhancement

#2530 Implement Application Default Credentials for the google connector
  connector/google/google.go
  connector/google/google_test.go
Labels: kind/enhancement, area/connector, release-note/enhancement

#2648 build: bump Go version to 1.19 in Nix
  flake.lock
  flake.nix
Labels: kind/enhancement

#2656 chore: update alpine version in Go image
  Dockerfile
Labels: release-note/dependency-update

#2659 Reduce HTTP client creations in the Keystone connector
  connector/keystone/keystone.go
  connector/keystone/keystone_test.go
Labels: kind/enhancement, release-note/enhancement

#2679 fix for issue 2670; check for no serviceAccountFilePath and no email
  connector/google/google.go
  connector/google/google_test.go
Labels: release-note/bug-fix

#2683 supply HMACKey in test case
  storage/conformance/transactions.go
Labels: kind/bug

#2688 Update golang.org/x packages
  go.mod
  go.sum
Labels: area/dependencies

#2691 docs: Add Argo CD to list of Dex adopters
  ADOPTERS.md
Labels: release-note/ignore
