Repository dexidp/dex, pull requests merged in 2023-07, with the labels that each got.

#2806 RFC 8693 OAuth 2.0 Token Exchange
  cmd/dex/config.go
  cmd/dex/config_test.go
  cmd/dex/serve.go
  connector/connector.go
  connector/mock/connectortest.go
  connector/oidc/oidc.go
  connector/oidc/oidc_test.go
  server/handlers.go
  server/handlers_test.go
  server/oauth2.go
  server/oauth2_test.go
  server/refreshhandlers.go
  server/server.go
  server/server_test.go
Labels: release-note/new-feature

#3027 include granttypes in example config
  examples/config-dev.yaml
Labels: kind/enhancement

#2972 Add GetClient grpc service
  api/v2/api.pb.go
  api/v2/api.proto
  api/v2/api_grpc.pb.go
  server/api.go
Labels: kind/enhancement

#2521 feat: Update response_types_supported to allow multiple-valued response type combinations
  server/oauth2.go
  server/server.go
Labels: kind/enhancement, area/oidc-spec
