Repository dexidp/dex, pull requests merged in 2023-12, with the labels that each got.

#3232 Bump golangci-lint 1.55.2
  .golangci.yml
  Makefile
Labels: release-note/dependency-update

#3234 Patch gomplate to v3.11.6
  Dockerfile
Labels: area/dependencies

#2851 Add support for extra claims to authproxy connector
  connector/authproxy/authproxy.go
  connector/authproxy/authproxy_test.go
Labels: kind/enhancement

#3247 Fix lint errors after merging AllowedHeaders feature
  cmd/dex/config.go
  cmd/dex/serve.go
  server/server.go
Labels: release-note/bug-fix

#3248 Remove user-facing changes section from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note/ignore

#3249 Bump dependencies ent v0.12.5, protobuf v1.32.0
  Makefile
  api/v2/go.mod
  api/v2/go.sum
  go.mod
  go.sum
  storage/ent/db/authcode_update.go
  storage/ent/db/authrequest_update.go
  storage/ent/db/client.go
  storage/ent/db/connector_update.go
  storage/ent/db/devicerequest_update.go
  storage/ent/db/devicetoken_update.go
  storage/ent/db/keys_update.go
  storage/ent/db/oauth2client_update.go
  storage/ent/db/offlinesession_update.go
  storage/ent/db/password_update.go
  storage/ent/db/refreshtoken_update.go
  storage/ent/db/runtime/runtime.go
Labels: area/dependencies

#3189 Add support for linux/s390x
  .github/workflows/artifacts.yaml
Labels: kind/enhancement
