Repository dexidp/dex, pull requests merged in 2023-03, with the labels that each got.

#2805 Skip redirection to approval when it is not required (#2686)
  server/handlers.go
  server/handlers_test.go
  server/server_test.go
Labels: release-note/enhancement

#2844 feat: Bump dependencies and Makefile refactoring
  .github/workflows/ci.yaml
  .golangci.yml
  Makefile
  connector/openshift/openshift.go
  go.mod
  go.sum
  storage/ent/db/client.go
  storage/ent/db/config.go
  storage/ent/db/context.go
  storage/ent/db/ent.go
  storage/ent/db/mutation.go
  storage/ent/db/runtime/runtime.go
Labels: kind/enhancement

#2840 feat: Bump gomplate 3.11.4
  Dockerfile
Labels: release-note/dependency-update

#2858 fix: Run go mod tidy last (fix verify command)
  Makefile
  go.sum
Labels: release-note/ignore

#2812 DEP for RFC 8693 OAuth 2 Token Exchange
  docs/enhancements/token-exchange-2023-02-03-#2812.md
Labels: release-note/ignore

#2857 Fix verify
  .golangci.yml
  Makefile
  flake.lock
  flake.nix
  go.mod
  go.sum
  storage/ent/db/authcode/where.go
  storage/ent/db/authrequest/where.go
  storage/ent/db/connector/where.go
  storage/ent/db/ent.go
  storage/ent/db/keys/where.go
  storage/ent/db/oauth2client/where.go
  storage/ent/db/offlinesession/where.go
  storage/ent/db/refreshtoken/where.go
  storage/ent/db/runtime/runtime.go
Labels: release-note/ignore

#2870 chore: upgrade tools
  Makefile
  api/api.pb.go
  api/api_grpc.pb.go
  api/v2/api.pb.go
  api/v2/api_grpc.pb.go
  server/internal/types.pb.go
Labels: area/dependencies
