Repository dexidp/dex, pull requests merged in 2023-05, with the labels that each got.

#2919 Spelling
  .github/SECURITY.md
  api/api.pb.go
  api/api.proto
  api/v2/api.pb.go
  api/v2/api.proto
  config.yaml.dist
  connector/gitlab/gitlab.go
  connector/google/google_test.go
  connector/ldap/ldap.go
  connector/ldap/ldap_test.go
  connector/oidc/oidc.go
  docs/enhancements/token-exchange-2023-02-03-#2812.md
  server/api_test.go
  server/deviceflowhandlers_test.go
  server/server.go
  server/server_test.go
  storage/conformance/conformance.go
  storage/kubernetes/client.go
  storage/storage.go
Labels: kind/enhancement

#2921 Improve CI
  .github/workflows/analysis-scorecard.yaml
  .github/workflows/artifacts.yaml
  .github/workflows/ci.yaml
  .github/workflows/codeql-analysis.yaml
  .github/workflows/docker.yaml
  .github/workflows/release.yaml
  README.md
Labels: release-note/ignore

#2829 LDAP case-insensitive DN attribute
  connector/ldap/ldap.go
  connector/ldap/ldap_test.go
Labels: kind/enhancement

#2967 Comment the flaky debugging stage
  .github/workflows/artifacts.yaml
Labels: release-note/ignore

#2937 Fail if OIDC config contains hosted domains
  connector/oidc/oidc.go
Labels: kind/bug
