Repository dexidp/dex, pull requests merged in 2023-10, with the labels that each got.

#3125 Store offline sessions only if they were requested by the user
  server/handlers.go
  server/handlers_test.go
Labels: kind/enhancement

#3165 Bump Go 1.21
  .github/workflows/ci.yaml
  Dockerfile
  go.mod
  go.sum
Labels: area/dependencies

#3082 Mark token refresh as supported by OpenShift connector
  README.md
Labels: release-note/ignore

#3166 Bump ent (v0.12.4) and example app dependencies
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  storage/ent/db/authcode/where.go
  storage/ent/db/authcode_create.go
  storage/ent/db/authrequest/where.go
  storage/ent/db/authrequest_create.go
  storage/ent/db/client.go
  storage/ent/db/connector/where.go
  storage/ent/db/connector_create.go
  storage/ent/db/devicerequest/where.go
  storage/ent/db/devicerequest_create.go
  storage/ent/db/devicetoken/where.go
  storage/ent/db/devicetoken_create.go
  storage/ent/db/keys/where.go
  storage/ent/db/keys_create.go
  storage/ent/db/oauth2client/where.go
  storage/ent/db/oauth2client_create.go
  storage/ent/db/offlinesession/where.go
  storage/ent/db/offlinesession_create.go
  storage/ent/db/password/where.go
  storage/ent/db/password_create.go
  storage/ent/db/refreshtoken/where.go
  storage/ent/db/refreshtoken_create.go
  storage/ent/db/runtime/runtime.go
Labels: area/dependencies

#3074 Minimalistic support for group filtering in oidc connector
  connector/oidc/oidc.go
Labels: release-note/enhancement

#3084 feat(connector/microsoft): support custom api and graph URLs
  connector/microsoft/microsoft.go
Labels: kind/enhancement, area/connector
