Repository dexidp/dex, pull requests merged in 2024-04, with the labels that each got.

#3459 chore: run release note label ci only in dexidp/dex repo not in forks
  .github/workflows/checks.yaml
Labels: release-note/ignore

#3458 use the default cosign version from the action
  .github/workflows/artifacts.yaml
Labels: release-note/dependency-update

#3470 Do not escape password for LDAP connectors
  connector/ldap/ldap.go
Labels: kind/bug

#3471 Backport fixes to v2.39.1
  connector/ldap/ldap.go
  storage/kubernetes/client.go
Labels: release-note/ignore

#3475 feat: Add support for configurable prompt type for Google connector
  connector/google/google.go
  connector/google/google_test.go
  connector/oidc/oidc.go
Labels: kind/enhancement
