Repository dexidp/dex, pull requests merged in 2024-01, with the labels that each got.

#3293 Bump gomplate to v3.11.7
  Dockerfile
Labels: kind/enhancement

#3280 Pin actions and container image dependencies
  .github/workflows/checks.yaml
  .github/workflows/ci.yaml
  Dockerfile
Labels: release-note/ignore

#3278 Introduce a dedicated pkg for featureflags
  cmd/dex/config.go
  pkg/featureflags/flag.go
  pkg/featureflags/set.go
Labels: kind/enhancement

#3268 Add dependabot for example app
  .github/dependabot.yaml
Labels: kind/enhancement, release-note/ignore

#3276 Propagate Dex version from build args
  Dockerfile
Labels: kind/bug

#3269 Sign container images
  .github/workflows/artifacts.yaml
Labels: release-note/enhancement

#2935 Add context to storage's Create endpoints
  server/api.go
  server/api_test.go
  server/deviceflowhandlers.go
  server/deviceflowhandlers_test.go
  server/handlers.go
  server/handlers_test.go
  server/refreshhandlers_test.go
  server/server_test.go
  storage/conformance/conformance.go
  storage/conformance/transactions.go
  storage/ent/client/authcode.go
  storage/ent/client/authrequest.go
  storage/ent/client/client.go
  storage/ent/client/connector.go
  storage/ent/client/devicerequest.go
  storage/ent/client/devicetoken.go
  storage/ent/client/offlinesession.go
  storage/ent/client/password.go
  storage/ent/client/refreshtoken.go
  storage/etcd/etcd.go
  storage/health.go
  storage/kubernetes/storage.go
  storage/kubernetes/storage_test.go
  storage/memory/memory.go
  storage/memory/static_test.go
  storage/sql/crud.go
  storage/static.go
  storage/storage.go
Labels: kind/enhancement

#3303 feat: add TLS versions configuration
  cmd/dex/config.go
  cmd/dex/config_test.go
  cmd/dex/serve.go
  config.yaml.dist
Labels: kind/enhancement

#3307 Also set the username in authproxy connector
  connector/authproxy/authproxy.go
  connector/authproxy/authproxy_test.go
Labels: kind/enhancement
