Repository dexidp/dex, pull requests merged in 2024-08, with the labels that each got.

#3063 add regex for oidc group matching
  connector/oidc/oidc.go
  connector/oidc/oidc_test.go
Labels: kind/enhancement

#3661 Enrich Dex logs with real IP and request ID
  cmd/dex/config.go
  cmd/dex/logger.go
  cmd/dex/serve.go
  examples/config-dev.yaml
  server/deviceflowhandlers.go
  server/handlers.go
  server/introspectionhandler.go
  server/introspectionhandler_test.go
  server/oauth2.go
  server/refreshhandlers.go
  server/server.go
Labels: release-note/new-feature

#3663 Remove additional features and add a feature flag instead
  cmd/dex/config.go
  cmd/dex/config_test.go
  cmd/dex/serve.go
  examples/config-dev.yaml
  pkg/featureflags/set.go
  server/api.go
  server/api_test.go
  server/server.go
Labels: release-note/bug-fix

#3669 Migrate to docker compose plugin
  .github/workflows/ci.yaml
Labels: release-note/ignore

#3670 Bump ent v0.14.0
  go.mod
  go.sum
  storage/ent/db/authcode_query.go
  storage/ent/db/authrequest_query.go
  storage/ent/db/connector_query.go
  storage/ent/db/devicerequest_query.go
  storage/ent/db/devicetoken_query.go
  storage/ent/db/ent.go
  storage/ent/db/keys_query.go
  storage/ent/db/oauth2client_query.go
  storage/ent/db/offlinesession_query.go
  storage/ent/db/password_query.go
  storage/ent/db/refreshtoken_query.go
  storage/ent/db/runtime/runtime.go
Labels: area/dependencies

#3677 Fix scheme for DialURL ldap connection
  .github/workflows/ci.yaml
  connector/ldap/ldap.go
  docker-compose.test.yaml
Labels: kind/bug

#3684 Change workdir for gomplate
  cmd/docker-entrypoint/main.go
  cmd/docker-entrypoint/main_test.go
Labels: kind/bug

#3700 chore: update nix-direnv from 1.5.0 to 3.0.5
  .envrc
Labels: release-note/ignore

#3598 Added Discovery to grpc
  api/v2/api.pb.go
  api/v2/api.proto
  api/v2/api_grpc.pb.go
  cmd/dex/serve.go
  server/api.go
  server/api_test.go
  server/handlers.go
Labels: kind/enhancement
