Repository dexidp/dex, pull requests merged in 2024-10, with the labels that each got.

#3778 feat: also allow localhost equivalent IP addresses
  server/oauth2.go
  server/oauth2_test.go
Labels: release-note/new-feature

#3793 saml connector: fix nil pointer PANIC on validate saml
  connector/saml/saml.go
Labels: kind/bug

#3755 fix: update enhancement proposal link
  .github/ISSUE_TEMPLATE/config.yml
Labels: kind/bug

#3747 Handle root path better (than nothing)
  server/server.go
Labels: kind/enhancement

#3751 Support base64 encoded and PEM encoded certs
  pkg/httpclient/httpclient.go
  pkg/httpclient/httpclient_test.go
Labels: kind/enhancement

#2941 GitLab connector: add GitLab additional group with role
  connector/gitlab/gitlab.go
  connector/gitlab/gitlab_test.go
Labels: kind/enhancement

#3819 Fix trivydb TOOMANYREQUESTS error
  .github/workflows/artifacts.yaml
Labels: release-note/ignore

#3821 Update trivydb cache on the begging of each day
  .github/workflows/artifacts.yaml
  .github/workflows/trivydb-cache.yaml
Labels: release-note/ignore
