Repository dexidp/dex, pull requests merged in 2024-07, with the labels that each got.

#3589 Gracefully handle no args being passed to entrypoint
  cmd/docker-entrypoint/main.go
Labels: kind/enhancement

#3558 feat: new Prometheus metrics build_info
  cmd/dex/serve.go
Labels: kind/enhancement

#3584 fix: always retrieve github emails when `preferredEmailDomain` is set
  connector/github/github.go
Labels: kind/enhancement, area/connector

#3245 gRPC Connectors API
  api/v2/api.pb.go
  api/v2/api.proto
  api/v2/api_grpc.pb.go
  cmd/dex/config.go
  cmd/dex/config_test.go
  cmd/dex/serve.go
  examples/config-dev.yaml
  server/api.go
  server/api_test.go
  server/server.go
Labels: kind/enhancement

#3641 fix: propagate http.Client to JWT verifier for OIDC connector
  connector/oidc/oidc.go
Labels: release-note/enhancement

#3648 README: Fix the broken link to v2 page
  README.md
Labels: kind/enhancement

#3637 Update dependencies before Dex v2.41
  .github/workflows/artifacts.yaml
  Dockerfile
  api/v2/go.mod
  api/v2/go.sum
  connector/google/google.go
  connector/ldap/ldap.go
  examples/config-dev.yaml
  go.mod
  go.sum
Labels: area/dependencies, dependencies

#3653 FIx CVE before Dex v2.41
  api/v2/go.mod
  api/v2/go.sum
Labels: area/dependencies

#3652 Bump gomplate 4.0.1
  Dockerfile
Labels: area/dependencies

#3650 Update README: Add a link to release process in Development section
  README.md
Labels: release-note/ignore
