Repository dexidp/dex, pull requests merged in 2024-05, with the labels that each got.

#3464 chore: fix function names in comment
  connector/saml/saml.go
  storage/ent/db/ent.go
Labels: kind/bug

#3528 Revert autogenerated columnChecker description
  storage/ent/db/ent.go
Labels: release-note/ignore

#3548 introduce Provenance Attestation
  .github/workflows/artifacts.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: release-note/ignore

#2989 Google: Implement groups fetch by default service account from metadata (support for GKE workload identity)
  connector/google/google.go
  connector/google/google_test.go
  go.mod
  go.sum
Labels: release-note/enhancement

#3538 Fix slight grammar errors.
  README.md
Labels: kind/bug

#3553 Bump google.golang.org/grpc to v1.64.0
  api/v2/go.mod
  api/v2/go.sum
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  server/api_test.go
Labels: release-note/dependency-update

#3543 OIDC connector option to override jwksURI
  connector/oidc/oidc.go
Labels: kind/enhancement

#2918 Look for secrets before using them
  .github/workflows/artifacts.yaml
Labels: release-note/ignore
