Repository dexidp/dex, pull requests merged in 2024-03, with the labels that each got.

#3409 Update jose
  connector/oauth/oauth_test.go
  connector/oidc/oidc_test.go
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  server/handlers.go
  server/oauth2.go
  server/oauth2_test.go
  server/rotation.go
  server/server_test.go
  storage/conformance/conformance.go
  storage/conformance/gen_jwks.go
  storage/conformance/jwks.go
  storage/ent/db/keys.go
  storage/ent/db/keys_create.go
  storage/ent/db/keys_update.go
  storage/ent/db/mutation.go
  storage/ent/schema/keys.go
  storage/etcd/types.go
  storage/kubernetes/types.go
  storage/storage.go
Labels: area/dependencies, dependencies

#3372 fix: add sanitizer to ldap account and password
  connector/ldap/ldap.go
  connector/ldap/ldap_test.go
Labels: kind/enhancement

#3339 Add headers control to dex web server
  cmd/dex/config.go
  cmd/dex/config_test.go
  cmd/dex/serve.go
  examples/config-dev.yaml
  server/server.go
  server/server_test.go
Labels: kind/enhancement

#3373 OIDC connector: Allow specifying empty prompt type
  connector/oidc/oidc.go
  connector/oidc/oidc_test.go
Labels: kind/enhancement

#3415 Set read only permissions to the check job
  .github/workflows/checks.yaml
Labels: kind/enhancement

#3404 [RFC7662] Add introspect endpoint to introspect access & refresh token
  server/handlers.go
  server/handlers_test.go
  server/introspectionhandler.go
  server/introspectionhandler_test.go
  server/oauth2.go
  server/oauth2_test.go
  server/refreshhandlers.go
  server/server.go
Labels: kind/enhancement

#3432 Update Distroless to Debian 12
  Dockerfile
Labels: kind/enhancement

#3439 Update max length of kubernetes object to fit kubernetes policy
  storage/kubernetes/client.go
Labels: kind/bug

#3441 fix: wrong error code returned in case of inactive token
  server/introspectionhandler.go
  server/introspectionhandler_test.go
Labels: release-note/ignore
