Repository dexidp/dex, pull requests merged in 2024-06, with the labels that each got.

#3506 feat: allow domain names or IDs in keystone connector
  connector/keystone/keystone.go
  connector/keystone/keystone_test.go
  go.mod
Labels: kind/enhancement

#3560 Build containers for branches
  .github/workflows/artifacts.yaml
Labels: release-note/ignore

#3563 Fix slog nil pointer error
  cmd/dex/serve.go
  cmd/dex/serve_test.go
Labels: release-note/ignore

#3564 Fix trivy scanning job
  .github/workflows/artifacts.yaml
Labels: release-note/ignore

#3565 Bump gomplate 3.11.8
  Dockerfile
Labels: release-note/dependency-update

#3554 Prevent double clicking of the submit button on login
  web/static/main.css
  web/templates/password.html
Labels: kind/enhancement
