Repository dexidp/dex, pull requests merged in 2025-05, with the labels that each got.

#4097 docs: Split Adopters to Companies and Projects
  ADOPTERS.md
Labels: release-note/ignore

#4082 fix Incorrect Group Handling in RequestContextHandler logger.go
  cmd/dex/logger.go
Labels: kind/bug

#4141 chore: update dependencies
  api/v2/go.mod
  api/v2/go.sum
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  storage/ent/db/runtime/runtime.go
Labels: area/dependencies

#4146 Resolve CVE by updating gomplate to 4.3.2
  Dockerfile
Labels: area/dependencies
